# docker file for predictive-analytics-service.py

FROM python:3.7

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

COPY . /app

WORKDIR /app

EXPOSE 8080

CMD ["python", "predictive-analytics-service.py"]