version: '3.7'

services:
  user-interface-grafana:
    image: grafana/grafana
    container_name: user-interface-grafana
    volumes:
      - ./user-interface-grafana:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - pesco
    depends_on:
      - mqtt_broker

  mqtt_broker:
    image: eclipse-mosquitto:2.0.10
    container_name: mqtt_broker
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    # restart: always
    ports:
      - 1883:1883
    networks:
      - pesco

  mqtt_check:
    image: eclipse-mosquitto:2.0.10
    container_name: mqtt_check
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    # restart: always
    ports:
      - 1884:1883
    networks:
      - pesco

  energy-data-aggregator:
    build: energy-data-aggregator
    container_name: energy-data-aggregator
    ports:
      - 8082:8080
    networks:
      - pesco
    depends_on:
      - mqtt_broker

  dynamic-price-calculator:
    build: dynamic-price-calculator
    container_name: dynamic-price-calculator
    ports:
      - 8083:8080
    networks:
      - pesco
    depends_on:
      - mqtt_broker

  predictive-analytics-service:
    build: predictive-analytics-service
    container_name: predictive-analytics-service
    ports:
      - 8081:8080
    networks:
      - pesco
    depends_on:
      - mqtt_broker

networks:
  pesco:
